name: comet_env

channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.9
  - pytorch=1.12.0
  - cudatoolkit=11.3
  - h5py
  - matplotlib
  - numba
  - numpy
  - pandas
  - pip
  - pyyaml
  - scipy

  - pip:
    - cerberus
