[build-system]
requires    = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name              = "py-comet"
version           = "1.0.1"
description       = "Drift correction for single molecule localization microscopy datasets"
readme            = "README.md"
license = { text = "MIT" }
requires-python   = ">=3.8,<3.12"
authors           = [
  { name = "Lenny Reinkensmeier", email = "lenny.reinkensmeier@ifnano.de" },
  { name = "Mark Bates", email = "mark.bates@ifnano.de" }
]
dependencies = [
  "numpy>=1.20.0,<2.0",
  "scipy>=1.10.0,<=1.16.3",
  "matplotlib>=3.1.0,<3.8",
  "pandas>=2.0.0",
  "h5py>=3.11.0",
  "numba>=0.58.0,<=0.62.1",
  "scikit-learn>=1.3.0,<=1.7",
  "lmfit>=1.3.0",
]



[project.optional-dependencies]
light = ["numba>=0.58.0,<=0.62.1"]

[project.urls]
Homepage    = "https://github.com/yourusername/comet-drift"
Repository  = "https://github.com/yourusername/comet-drift"

[tool.setuptools.packages.find]
where   = ["."]
include = ["comet*"]

[project.scripts]
comet = "comet.cli.cli_interface:main"
comet_self_test = "comet.tests.self_test:main"
